register/manager/urls.py
from django.urls import path

from . import views

app_name = "manager"

urlpatterns = [
    path(r'', views.InitialView, name="initial-view"),
    path(r'registration-list/', views.RegistrationList, name="registration-list"),
    path(r'user-registration/', views.UserRegistration, name="user-registration"),
    path(r'user-registration/confirmation-of-registration', views.FinishRegister, name="confirmation-of-registration")
]

register/register/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'register/', include('manager.urls', namespace='manager'))    
]

register/manager/models.py
from django.db import models



class Post(models.Model):
    STAGE_CHOICE = (
        ('Aguardando assinatura de documentos','Aguardando assinatura de documentos'),
        ('Aguardando transferência de recursos','Aguardando transferência de recursos'),
        ('Gestão de patrimônio ativa','Gestão de patrimônio ativa')
    )

    name = models.CharField(max_length=255)
    cpf = models.CharField(max_length=11)
    stage = models.CharField(max_length=50, choices=STAGE_CHOICE)

    # Keep storage what time was created and the last time it was updated
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

register/manager/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('name', 'cpf', 'stage')

register/manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.views.generic import ListView
from django.template import loader
#from rest_framework.decorators import api_view
from django.http.response import JsonResponse
#from rest_framework.parsers import JSONParser

from .models import Post
from .forms import PostForm

def InitialView(request):
    return render(request, 'manager/initial-view.html')

def UserRegistration(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()      
            return redirect('manager:confirmation-of-registration')
    else:
        form = PostForm()
    return render(request, 'manager/user_registration.html', {'form': form})

#@api_view(['GET', 'POST', 'PUT'])
def RegistrationList(request):
    try:
        latest_registration_list = Post.objects.order_by('-updated')
        template = loader.get_template('manager/registration_list.html')
        context = {
            'latest_registration_list' : latest_registration_list,
        }        
        return render(request, 'manager/registration_list.html', context)
    except:
        return Http404()

def FinishRegister(request):
    return render(request, 'manager/confirmation-of-registration.html')

register/manager/templates/manager/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <title> {% block title %} {% endblock %} </title>
        <link href="{% static 'css/manager.css' %}" rel="stylesheet">
        <meta charset="utf-8">
    </head>
    <body>
        <header class='head-base'>
            <h1>CVD User Registration System</h1>
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>

</html>

register/manager/templates/manager/confirmation-of-registration.html
{% extends "manager/base.html" %}

{% block title %} Registration Confirm {% endblock %}

{% block content %}

    <div style="color: whitesmoke;" class="options">
        <p>User register successfully!</p>
    </div>

    <div class="final-link">
        <a href= {% url 'manager:initial-view' %}> Home </a>
    </div>

{% endblock %}

register/manager/templates/manager/initial-view.html
{% extends "manager/base.html" %}

{% block title %} Registration Option {% endblock %}

{% block content %}

    <div class="options">
        <form method="POST" action= {% url 'manager:user-registration' %}> 
            {% csrf_token %}
            <input type="submit" value="Register a new user">            
        </form>              
        <br>
        <form method="POST" action= {% url 'manager:registration-list' %}>
            {% csrf_token %}
            <input type="submit" value="List all users">            
        </form>
    </div>

{% endblock %}

register/manager/templates/manager/registration_list.html
{% extends "manager/base.html" %}

{% block title %}Registration List{% endblock %}


{% block content %}    
    {% if latest_registration_list %}
        <ul class='main-register-list'>
        {%for reg in latest_registration_list %}
            <li>
                <div class="user-data-list">
                    <ul>
                        <li>Nome: {{ reg.name }}</li>
                        <li>CPF: {{ reg.cpf }}</li>
                        <li>Etapa: {{ reg.stage }}</li>
                        <hr>
                    </ul>
                </div>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No registers are available.</p>
    {% endif %}

    <div class="final-link">
        <a href= {% url 'manager:initial-view' %}> Home </a>
    </div>
{% endblock %}

register/manager/templates/manager/user_registration.html
{% extends "manager/base.html" %}

{% block title %} Registration {% endblock %}

{% block content %}
    <div class="reg-form">
        <h2>User Registration</h2>
        <form method="POST" class="user-data post-form">{% csrf_token %}
            {{ form.as_p }}
            <div class="btn-save">
                <button type="submit" class="save btn btn-default">Save</button>
            </div>
        </form>
    </div>

    <div class="final-link">
        <a href= {% url 'manager:initial-view' %}> Home </a>
    </div>

{% endblock %}